### ISSUE TITLE
Improve performance of the event look up in sample

### ISSUE THREAD

**Issue by rexim** [tsoding/midi-looper#153]
### Description

Events look up takes linear time. If we group events by quant number we can improve it up to `O(1)`.

### Performance comparison

  | Implementation | Time                         |
  |----------------|:------------------------------|
  | BTreeMap       | 1,203 ns/iter (+/- 259)      |
  | Linear         | 1,265 ns/iter (+/- 389)      |
  | HashMap        | 163,339 ns/iter (+/- 39,655) |

### Todo

- [ ] Compare with fnv crate https://crates.io/crates/fnv
- [ ] Use real recorded data for benchmarking
- [ ] Test in release mode
- [ ] Key is a number, try just a plain array -_-

**Comment by rexim** [comment]
It'd be also great to measure the performance and see the difference after the improvement. Maybe some kind of benchmarks

**Comment by rexim** [comment]
| Implementation | Time                         |
  |----------------|:------------------------------|
  | BTreeMap       | 1,203 ns/iter (+/- 259)      |
  | Linear         | 1,265 ns/iter (+/- 389)      |
  | HashMap        | 163,339 ns/iter (+/- 39,655) |
