### ISSUE TITLE
UI port select on start

### ISSUE THREAD

**Issue by rexim** [tsoding/midi-looper#169]
When the application is started the user is presented with a UI list of available input and output devices to choose from.

This feature should supersede the device configuration from CLI.

### Pieces

- [x] #68 Configuration
- [x] ~~#191 Implement Port Selection State~~
- [x] ~~#190 Implement state switcher and incorporte Port Selection State in it~~
- [x] #205 Replace state mechanism with screens mechanism
- [ ] #226 Port selection Screen
