### ISSUE TITLE
Play from regular computer keyboard

### ISSUE THREAD

**Issue by rexim** [tsoding/midi-looper#49]
### Description

Sometimes I don't have any MIDI keyboard nearby, but still want to play with the MIDI looper. It would be cool to be able to play from a regular computer keyboard. :)

### Pieces

- [x] #215 Add mapping between regular keyboard keycodes and midi keys
- [x] #216 Unhardcode regular keyboard MIDI mapping
- [ ] #218 Screen for creating and exporting regular keyboard MIDI mappings
- [ ] #217 Calculate current timestamp with PortMidi mechanisms
- [ ] #219 Default regular keyboard MIDI mapping
