### ISSUE TITLE
Exporting and importing loops

### ISSUE THREAD

**Issue by rexim** [tsoding/midi-looper#51]

**Comment by rexim** [comment]
The issue is split at #173 

### Pieces
- [x] #174 Make Sample decodable
- [x] #175 Make State Looper encodable/decodable
- [x] #176 Save/load looper to/from file system
